/**
 * Share link generation.
 *
 * Ported from tests/pure/test_share_service.py with its assertions intact,
 * plus full-URI fixture scenarios generated by the frozen Python service:
 * the substring assertions catch intent, the fixtures pin every byte.
 */

import { describe, expect, it } from "vitest";

import { pyQuote } from "../../src/core/python_uri";
import { base64UrlEncode, derivePublicKey } from "../../src/core/x25519";
import {
  hasUsableAddress,
  linksForUser,
  type LinkUser,
  type ShareLink,
} from "../../src/services/share_service";
import fixture from "../fixtures/share_service.json";

/** WHAT: one fixture scenario, widened from the JSON import's narrow types. */
type FixtureScenario = {
  name: string;
  user: LinkUser;
  configured_address: string;
  reality_keys: Record<string, string> | null;
  profiles: Record<string, Record<string, unknown>[]> | null;
  node_label: string | null;
  labels: Record<string, string> | null;
  links: ShareLink[];
  warnings: string[];
};

const UUID = "11111111-1111-1111-1111-111111111111";

/** WHAT: decode a hex string into bytes without Node's Buffer. */
function bytesFromHex(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let index = 0; index < bytes.length; index++) {
    bytes[index] = parseInt(hex.slice(index * 2, index * 2 + 2), 16);
  }
  return bytes;
}

/** WHAT: a config that exercises raw/reality, xhttp, and ws. */
function shareConfig(): Record<string, unknown> {
  return {
    inbounds: [
      {
        tag: "REALITY_IN",
        protocol: "vless",
        listen: "0.0.0.0",
        port: 443,
        settings: { flow: "xtls-rprx-vision" },
        streamSettings: {
          network: "raw",
          security: "reality",
          realitySettings: {
            serverNames: ["apple.com"],
            privateKey: "sMS4KcvOCag9dZsYPa3sFfVLSn3IGNEI34B7ENhGBFE",
            shortIds: ["1234"],
          },
        },
      },
      {
        tag: "XHTTP_IN",
        protocol: "vless",
        listen: "203.0.113.5",
        port: 8080,
        streamSettings: {
          network: "xhttp",
          xhttpSettings: {
            path: "/xhttp-path",
            host: "xhttp.example.com",
            mode: "auto",
          },
        },
      },
      {
        tag: "WS_IN",
        protocol: "vless",
        listen: "::",
        port: 8443,
        streamSettings: {
          network: "ws",
          wsSettings: {
            path: "/ws-path",
            host: "ws.example.com",
          },
        },
      },
      { tag: "HTTP_ONLY", protocol: "http", port: 80 },
    ],
    outbounds: [
      { tag: "JAPAN", protocol: "freedom" },
      { tag: "HK", protocol: "freedom" },
    ],
  };
}

/** WHAT: a test user; default inbounds exclude the non-VLESS one. */
function shareUser(
  inbounds?: string[],
  outbounds?: string[],
): LinkUser {
  const allowedOutbounds = outbounds ?? ["JAPAN"];
  return {
    username: "alice",
    status: "active",
    allowed_inbounds: inbounds ?? ["REALITY_IN", "XHTTP_IN", "WS_IN"],
    allowed_outbounds: allowedOutbounds,
    uuids: Object.fromEntries(
      allowedOutbounds.map((outbound) => [`alice@${outbound}`, UUID]),
    ),
  };
}

describe("linksForUser", () => {
  it("builds a correctly ordered raw REALITY URI", () => {
    const [links, warnings] = linksForUser(
      shareUser(["REALITY_IN"]),
      shareConfig(),
      "example.com",
    );

    expect(links).toHaveLength(1);
    const reality = links[0];
    expect(reality["outbound"]).toBe("JAPAN");
    expect(reality["uri"]).toContain("vless://11111111-");
    expect(reality["uri"]).toContain("example.com:443");
    expect(reality["uri"]).toContain("type=tcp");
    expect(reality["uri"]).toContain("security=reality");
    expect(reality["uri"]).toContain("sni=apple.com");
    expect(reality["uri"]).toContain(
      "pbk=w_OZ1uUriCcd12KatYIFBJulAFDGNp9V1wL_XiQBt08",
    );
    expect(reality["uri"]).toContain("sid=1234");
    expect(reality["uri"]).toContain("fp=chrome");
    expect(reality["uri"]).toContain("encryption=none");
    expect(reality["uri"]).toContain("flow=xtls-rprx-vision");
    expect(warnings).toEqual([]);
  });

  it("derives pbk from the panel's stored key over the config's", () => {
    // RFC 7748 §6.1 Alice's private key — a known-good stand-in
    const alice = "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a";
    const aliceBase64 = base64UrlEncode(bytesFromHex(alice));

    const [links] = linksForUser(
      shareUser(["REALITY_IN"]),
      shareConfig(),
      "example.com",
      { REALITY_IN: aliceBase64 },
    );

    const expected = derivePublicKey(aliceBase64);
    expect(links[0]["uri"]).toContain(`pbk=${expected}`);
    // differs from the config key's pbk -> the override really won
    expect(links[0]["uri"]).not.toContain(
      "pbk=w_OZ1uUriCcd12KatYIFBJulAFDGNp9V1wL_XiQBt08",
    );
  });

  it("falls back to the config value when the tag is absent", () => {
    const [links, warnings] = linksForUser(
      shareUser(["REALITY_IN"]),
      shareConfig(),
      "example.com",
      { OTHER_TAG: "whatever" },
    );

    expect(links[0]["uri"]).toContain(
      "pbk=w_OZ1uUriCcd12KatYIFBJulAFDGNp9V1wL_XiQBt08",
    );
    expect(warnings).toEqual([]);
  });

  it("uses the listen address, path, host, and mode for xhttp", () => {
    const [links, warnings] = linksForUser(
      shareUser(["XHTTP_IN"]),
      shareConfig(),
      "",
    );

    expect(links).toHaveLength(1);
    expect(links[0]["uri"]).toContain("203.0.113.5:8080");
    expect(links[0]["uri"]).toContain("type=xhttp");
    expect(links[0]["uri"]).toContain("path=%2Fxhttp-path");
    expect(links[0]["uri"]).toContain("host=xhttp.example.com");
    expect(links[0]["uri"]).toContain("mode=auto");
    expect(links[0]["uri"]).not.toContain("flow=");
    expect(warnings).toEqual([]);
  });

  it("skips a non-vless inbound with a warning", () => {
    const [links, warnings] = linksForUser(
      shareUser(["REALITY_IN", "HTTP_ONLY"]),
      shareConfig(),
      "example.com",
    );

    expect(links.map((link) => link["inbound"])).toEqual(["REALITY_IN"]);
    expect(warnings).toContain("skipping non-vless inbound 'HTTP_ONLY'");
  });

  it("warns about an unknown outbound", () => {
    const user = shareUser(["REALITY_IN"]);
    user["allowed_outbounds"] = ["NOWHERE"];

    const [links, warnings] = linksForUser(user, shareConfig(), "example.com");

    expect(links).toEqual([]);
    expect(warnings).toContain("unknown outbound 'NOWHERE'");
  });

  it("generates links for a disabled user with a warning", () => {
    const user = shareUser(["REALITY_IN"]);
    user["status"] = "disabled";

    const [links, warnings] = linksForUser(user, shareConfig(), "example.com");

    expect(links.length).toBeGreaterThan(0);
    expect(warnings).toContain("user alice is disabled");
  });

  it("ignores wildcard listens when no address is configured", () => {
    const [links, warnings] = linksForUser(shareUser(), shareConfig(), "");

    expect(links.map((link) => link["inbound"])).toEqual(["XHTTP_IN"]);
    expect(warnings).toContain("no address for inbound 'REALITY_IN'");
    expect(warnings).toContain("no address for inbound 'WS_IN'");
  });

  it("adds one profile variant per exit without changing the direct link", () => {
    const user = shareUser(["REALITY_IN", "XHTTP_IN", "WS_IN"], ["HK", "JAPAN"]);
    const profiles = {
      XHTTP_IN: [
        {
          id: "cdn",
          label: "CDN",
          overrides: { address: "cdn.example.com", port: 443 },
        },
      ],
    };

    const [links, warnings] = linksForUser(
      user,
      shareConfig(),
      "example.com",
      null,
      profiles,
    );

    // Three direct inbounds times two exits, plus the XHTTP profile once
    // for each of the two exits.
    expect(links).toHaveLength(8);
    expect(warnings).toEqual([]);
    const profileLinks = links.filter((link) => link["profile"] === "cdn");
    expect(profileLinks).toHaveLength(2);
    expect(profileLinks[0]["uri"]).toContain("cdn.example.com:443");
    expect(links[0]["profile"]).toBeNull();
    expect(links[0]["label"]).toBeNull();
    expect(links[0]["uri"]).toContain("#alice%40");
  });

  it("names direct and profile variants with labels", () => {
    const profiles = {
      XHTTP_IN: [
        {
          id: "cdn",
          label: "CDN",
          overrides: { address: "cdn.example.com", port: 443 },
        },
      ],
    };
    const labels = { XHTTP_IN: "XHTTP", JAPAN: "Japan" };

    const [links, warnings] = linksForUser(
      shareUser(["XHTTP_IN"]),
      shareConfig(),
      "example.com",
      null,
      profiles,
      "Tokyo 01",
      labels,
    );

    expect(warnings).toEqual([]);
    expect(links.map((link) => [link["profile"], link["label"]])).toEqual([
      [null, "Tokyo 01 · XHTTP → Japan"],
      ["cdn", "Tokyo 01 · CDN → Japan"],
    ]);
    expect(links[1]["uri"].endsWith(`#${pyQuote(links[1]["label"]!)}`)).toBe(true);
  });

  it("lets a profile supply an address the direct view lacks", () => {
    const profiles = {
      REALITY_IN: [
        {
          id: "cdn",
          label: "CDN",
          overrides: { address: "cdn.example.com", port: 443 },
        },
      ],
    };

    const [links, warnings] = linksForUser(
      shareUser(["REALITY_IN"]),
      shareConfig(),
      "",
      null,
      profiles,
    );

    expect(links).toHaveLength(1);
    expect(links[0]["profile"]).toBe("cdn");
    expect(links[0]["uri"]).toContain("cdn.example.com:443");
    expect(warnings).toContain("no address for inbound 'REALITY_IN'");
  });

  it("detects when at least one inbound has a real listen address", () => {
    expect(hasUsableAddress(shareConfig(), "example.com")).toBe(true);
    // With no configured address, XHTTP_IN's real IP is still usable.
    expect(hasUsableAddress(shareConfig(), "")).toBe(true);
    const onlyWildcard = { inbounds: [{ tag: "ONLY", listen: "0.0.0.0" }] };
    expect(hasUsableAddress(onlyWildcard, "")).toBe(false);
    expect(hasUsableAddress(onlyWildcard, "", ["cdn.example.com"])).toBe(true);
  });
});

describe("Python-generated link fixtures", () => {
  it("reproduces every scenario byte-for-byte", () => {
    for (const scenario of fixture.scenarios as unknown as FixtureScenario[]) {
      const [links, warnings] = linksForUser(
        scenario.user,
        fixture.config,
        scenario.configured_address,
        scenario.reality_keys,
        scenario.profiles,
        scenario.node_label,
        scenario.labels,
      );

      expect(links, scenario.name).toEqual(scenario.links);
      expect(warnings, scenario.name).toEqual(scenario.warnings);
    }
  });
});
